spring.application.name=Dine-in-order-api

spring.datasource.url=jdbc:mysql://localhost:3306/springboot_dine_in_order_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=argha@@argha
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

